name: Build and deploy to KurocoFront

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to KurocoFront
        run: |
          echo "Deploying to KurocoFront..."
